# Generated by Django 4.1.2 on 2022-10-22 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_workout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("short_description", models.TextField(max_length=50)),
                ("img", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="workouts",
            name="workout_time",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        3600, "The value must not exceed 3600 seconds"
                    )
                ]
            ),
        ),
    ]
