# Generated by Django 4.1.2 on 2022-10-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("first_workout", "0002_categories_alter_workouts_workout_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutsByDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.PositiveSmallIntegerField()),
                ("time_coefficient", models.FloatField()),
                ("is_completed", models.BooleanField()),
                (
                    "category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="first_workout.categories",
                        verbose_name="Category",
                    ),
                ),
                ("workouts", models.ManyToManyField(to="first_workout.workouts")),
            ],
        ),
    ]
